# Generated by Django 2.0.3 on 2018-03-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='postitem',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=15),
        ),
        migrations.AddField(
            model_name='postitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Category'),
        ),
    ]
